CREATE DATABASE jul_11;
USE jul_11;
CREATE TABLE product_info(id int,name varchar(20),description varchar(200),category varchar(150),status varchar(100),count int,productid bigint,price bigint);
USE jul_11;
CREATE TABLE notes_info(id int,title varchar(40),author varchar(200),publisher varchar(150),genre varchar(100),edition int,pubkish_date bigint,bookid bigint);
USE jul_11;
CREATE TABLE movie_info(id int,name varchar(40),producer varchar(200),actor varchar(150),cosinger varchar(100),count int,produce_date bigint,filmid bigint);
USE jul_11;
CREATE TABLE patient_info(id int,name varchar(40),doctor varchar(200),patient varchar(150),staffname varchar(100),count int,appoitment_date bigint,patientid bigint);
USE jul_11;
CREATE TABLE account_info(id int,name varchar(40),staff_name varchar(200),manager varchar(150),customer_name varchar(100),count int,salary_date bigint,staffid bigint);